const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
let storageOK=true,saved={};try{saved=JSON.parse(localStorage.getItem('sofra-v1')||'{}')||{}}catch{storageOK=false}
const state={person:['a','b'].includes(saved.person)?saved.person:'a',names:{a:'Kişi 1',b:'Kişi 2',...saved.names},start:/^\d{4}-\d{2}-\d{2}$/.test(saved.start||'')?saved.start:'2026-09-22',done:saved.done||{},shopping:saved.shopping||{}};
let tab=['today','week','shop','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'today',week=0;
const dateFor=i=>{const d=new Date(state.start+'T12:00:00');d.setDate(d.getDate()+i);return d};
const dayOffset=()=>Math.round((Date.UTC(new Date().getFullYear(),new Date().getMonth(),new Date().getDate())-Date.UTC(dateFor(0).getFullYear(),dateFor(0).getMonth(),dateFor(0).getDate()))/86400000);
let day=Math.max(0,Math.min(13,dayOffset()));
function save(){try{localStorage.setItem('sofra-v1',JSON.stringify(state));return true}catch{storageOK=false;toast('Kayıt saklanamadı. Tarayıcı depolama iznini kontrol edin.');return false}}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4000)}
const key=(id)=>`${localDate(dateFor(day))}:${state.person}:${id}`;
function summaryRows(items){return items.map(x=>{const total=typeof x.a==='number'&&typeof x.b==='number'?`${x.a+x.b} ${x.unit}`:x.name==='Orta boy dolma'?'5–7 adet':x.a==='Bol'?'İki kişilik':'Belirtilmemiş';return `<tr><td>${esc(x.name)}</td><td>${esc(x.a)} ${esc(x.unit)}</td><td>${esc(x.b)} ${esc(x.unit)}</td><td>${esc(total)}</td></tr>`}).join('')}
function card(m){const done=!!state.done[key(m.id)];return `<article class="meal ${done?'done':''}"><div class="meal-top"><span class="time">${m.time}</span><span class="tag">${m.id==='dinner'?'Ortak akşam yemeği':m.id==='breakfast'?'Kahvaltı':'İlk / öğle öğünü'}</span></div><div class="meal-body"><div><h3>${esc(m.title)}</h3><ul>${m.lines.map(l=>`<li>${esc(l)}</li>`).join('')}</ul></div><div class="art"><img src="art/${m.art}.svg" alt="${esc(m.title)} için temsili tabak çizimi"><small>Temsili çizim</small></div></div><div class="meal-footer"><span class="note">${esc(state.names[state.person])} için</span><button class="check ${done?'done':''}" data-meal="${m.id}" aria-pressed="${done}">${done?'✓ Yedim':'○ Yedim'}</button></div>${m.items?`<details><summary>İkimiz için ne hazırlayalım?</summary><div style="overflow-x:auto"><table><thead><tr><th>Yemek</th><th>${esc(state.names.a)}</th><th>${esc(state.names.b)}</th><th>Toplam</th></tr></thead><tbody>${summaryRows(m.items)}</tbody></table></div><p class="note">Et, balık, tahıl ve baklagiller pişmiş, yenebilir miktardır. Alışverişteki çiğ ağırlıkla aynı değildir.</p></details>`:''}</article>`}
function today(){const meals=mealsFor(day,state.person),count=meals.filter(m=>state.done[key(m.id)]).length,offset=dayOffset(),now=new Date(),minutes=now.getHours()*60+now.getMinutes(),start=state.person==='a'?720:540,inWindow=minutes>=start&&minutes<1200,next=meals.find(m=>{const [h,n]=m.time.split(':').map(Number);return h*60+n>minutes&&!state.done[key(m.id)]});
return `<p class="eyebrow">${esc(state.names[state.person])} · ${state.person==='a'?'12:00–20:00':'09:00–20:00'}</p><h1>Günün sofrası.</h1><div class="datebar"><button class="arrow" data-move="-1" ${day===0?'disabled':''} aria-label="Önceki gün">←</button><strong>${dateFor(day).toLocaleDateString('tr-TR',{day:'numeric',month:'long',weekday:'long'})} · ${day+1}/14</strong><button class="arrow" data-move="1" ${day===13?'disabled':''} aria-label="Sonraki gün">→</button></div>${offset<0?'<p class="notice">Plan henüz başlamadı. Seçtiğiniz günün menüsünü inceleyebilirsiniz. Başlangıcı Ayarlar’dan değiştirebilirsiniz.</p>':offset>13?'<p class="notice">14 günlük plan tamamlandı; yeni dönem için başlangıç tarihini Ayarlar’dan seçebilirsiniz.</p>':''}<section class="hero"><div><p class="eyebrow">${offset===day?'Şu anda':'Günün düzeni'}</p><b>${offset===day?(inWindow?'Beslenme aralığı':'Öğün arası'):'Aynı sofra, sana göre.'}</b><p>${offset===day&&next?`Sıradaki öğün ${next.time} · ${esc(next.title)}`:'Son öğünü 20:00’ye kadar tamamla.'}</p></div><span class="symbol" aria-hidden="true">◒</span></section><div class="sectionline"><h2>Günün öğünleri</h2><span class="note">${count} / ${meals.length} tamamlandı</span></div><div class="progress"><span style="width:${count/meals.length*100}%"></span></div><div class="meals">${meals.map(card).join('')}</div>${day<7||state.person==='b'?'<details class="notice"><summary>15:30 · Gerekirse ara öğün</summary><p>Seçeneklerden biri: 200 g sade yoğurt + küçük meyve; kefir + 10–15 badem; 1 haşlanmış yumurta + 1 dilim ekmek; 100–150 g lor + domates.</p><p>Ana öğünlerin yerine geçmez. İhtiyaç yoksa eklemeyin.</p></details>':''}<p class="note spacer">Bu menü aktarılan planın taslağıdır. Eksik gramajlar belirtilmiştir; günlük enerji ve protein toplamları doğrulanmamıştır.</p>`}
function plan(){return `<p class="eyebrow">Birlikte planlayın</p><h1>Önümüzdeki<br>14 gün.</h1><p class="muted">Bir güne dokunarak kişisel öğünleri ve porsiyonları açın.</p><div class="weekgrid">${dinners.map((d,i)=>`<button class="day" data-day="${i}"><small>${i+1}. GÜN · ${dateFor(i).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}</small><b>${esc(d[0])}</b><p>19:00 · Ortak akşam yemeği</p></button>`).join('')}</div>`}
function shop(){const list={};dinners.slice(week*7,week*7+7).forEach(d=>d[2].forEach(x=>{const name=x.name,old=list[name]||{n:0,unit:x.unit,unknown:false};if(typeof x.a==='number'&&typeof x.b==='number')old.n+=x.a+x.b;else old.unknown=true;list[name]=old}));return `<p class="eyebrow">Ortak mutfak</p><h1>Alışveriş<br>notlarımız.</h1><div class="tabs"><button data-week="0" class="${week===0?'active':''}">1. hafta</button><button data-week="1" class="${week===1?'active':''}">2. hafta</button></div><p class="notice">Aşağıdaki toplamlar yalnızca akşam yemeklerinin <b>pişmiş ihtiyaçlarıdır</b>; çiğ alışveriş gramajı değildir. Tarifler ve eksik miktarlar nedeniyle bu liste tam alışveriş hesabı sayılmaz.</p><h2>Akşam için</h2>${Object.entries(list).map(([name,x])=>shopRow(name,`${name} · ${x.n?x.n+' '+x.unit+(name==='Yoğurt'?'':' pişmiş'):''}${x.unknown?(x.n?' + miktarı belirtilmeyen öğün':'Miktarı / tarifi belirleyin'):''}`)).join('')}<h2 class="spacer">Diğer öğünleri kontrol et</h2><p class="note">Seçtiğiniz alternatiflere ve evdeki stoklara göre miktar belirleyin.</p>${['Yumurta','Tam buğday ekmeği / lavaş','Peynir / lor','Yoğurt / kefir / ayran','Öğle öğünleri için tavuk / et / balık','Domates, salatalık, biber, yeşillik','Meyve, çiğ badem','Zeytinyağı, limon, baharat','Dolma / köfte için tarif malzemeleri'].map(n=>shopRow('extra:'+n,n)).join('')}`}
function shopRow(id,label){const k=state.start+':'+week+':'+id;return `<label class="shopping"><input type="checkbox" data-shop="${esc(k)}" ${state.shopping[k]?'checked':''}><span>${esc(label)}</span></label>`}
function settings(){return `<p class="eyebrow">Size göre</p><h1>Sofranın düzeni.</h1><form id="settings-form"><div class="setting"><label for="name-a">12:00–20:00 planını kullanan kişi</label><input id="name-a" name="a" type="text" required maxlength="30" value="${esc(state.names.a)}"></div><div class="setting"><label for="name-b">09:00–20:00 planını kullanan kişi</label><input id="name-b" name="b" type="text" required maxlength="30" value="${esc(state.names.b)}"></div><div class="setting"><label for="start">14 günlük planın başlangıcı</label><input id="start" name="start" type="date" required value="${state.start}"><p class="note">Tarih değişirse eski işaretler eski tarihlerde kalır.</p></div><button class="primary" type="submit">Kaydet</button></form><h2 class="spacer">iPhone’a ekle</h2><p>Safari’de bu sayfayı açın. Paylaş menüsünden <b>Ana Ekrana Ekle</b> seçeneğine dokunun; görünüyorsa “Web Uygulaması Olarak Aç”ı etkinleştirin.</p><h2 class="spacer">Kayıtlarınız</h2><p class="note">İsimler, öğün ve alışveriş işaretleri yalnızca bu cihazın tarayıcısında tutulur. İki telefon arasında eşitlenmez. Site verileri silinirse kayıtlar kaybolur. Düzenli yedek alabilirsiniz.</p><div class="inline"><button id="export" class="secondary">Yedeği indir</button><label class="secondary" for="import">Yedekten yükle</label><input id="import" type="file" accept="application/json,.json" hidden></div><p class="note spacer">Sofra · 1.0<br>Temsili çizimler porsiyon ölçüsü değildir. Beslenme taslağı tedavi planı değildir. Otofaji saati veya garantisi hesaplanmaz.</p>`}
function render(){document.documentElement.lang='tr';$('#profile').textContent=state.names[state.person]+' ⇄';$('#app').innerHTML=(!storageOK?'<p class="notice">Bu tarayıcıda kalıcı kayıt kullanılamıyor.</p>':'')+({today,week:plan,shop,settings}[tab])();document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;if(tab==='today')day=Math.max(0,Math.min(13,dayOffset()));location.hash=tab;render();window.scrollTo(0,0)}if(b.id==='profile'){state.person=state.person==='a'?'b':'a';save();render()}if(b.dataset.move){day+=Number(b.dataset.move);render()}if(b.dataset.day){day=Number(b.dataset.day);tab='today';location.hash=tab;render();window.scrollTo(0,0)}if(b.dataset.meal){state.done[key(b.dataset.meal)]=!state.done[key(b.dataset.meal)];save();render()}if(b.dataset.week){week=Number(b.dataset.week);render()}if(b.id==='export'){const blob=new Blob([JSON.stringify({version:1,...state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sofra-yedek-'+localDate(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}});
document.addEventListener('submit',e=>{if(e.target.id!=='settings-form')return;e.preventDefault();const f=new FormData(e.target);state.names={a:String(f.get('a')).trim()||'Kişi 1',b:String(f.get('b')).trim()||'Kişi 2'};state.start=f.get('start');save();day=Math.max(0,Math.min(13,dayOffset()));render();toast('Tercihler kaydedildi.')});
document.addEventListener('change',async e=>{if(e.target.dataset.shop){state.shopping[e.target.dataset.shop]=e.target.checked;save()}if(e.target.id==='import'&&e.target.files[0]){try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!data.names||typeof data.names.a!=='string'||typeof data.names.b!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(data.start)||!Number.isFinite(new Date(data.start+'T12:00:00').getTime())||!data.done||typeof data.done!=='object'||!data.shopping||typeof data.shopping!=='object')throw Error();if(!confirm('Bu yedek cihazdaki mevcut takip kayıtlarının yerine yüklensin mi?'))return;Object.assign(state,{person:data.person==='b'?'b':'a',names:{a:data.names.a.slice(0,30),b:data.names.b.slice(0,30)},start:data.start,done:data.done,shopping:data.shopping});save();render();toast('Yedek yüklendi.')}catch{toast('Geçerli bir Sofra yedeği seçin.')}}});
window.addEventListener('hashchange',()=>{if(['today','week','shop','settings'].includes(location.hash.slice(1))){tab=location.hash.slice(1);render()}});
render();setInterval(()=>{if(tab==='today'&&!document.querySelector('details[open]'))render()},60000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('Çevrimdışı kullanım hazırlanamadı. İnternetle kullanabilirsiniz.'));
